version: '3.8'
services:
  orchestrator:
    container_name: orchestrator
    build:
      context: ./code/orchestrator
      dockerfile: Dockerfile
    volumes:
      - ./code/orchestrator:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - "~/.yarn/docker-cache:/home/node/.cache/yarn:cached"
      - "~/.npm/docker-cache:/home/node/.npm:cached" 
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    
  ms1:
    container_name: ms1
    build:
      context: ./code/ms1
      dockerfile: Dockerfile
    volumes:
      - ./code/ms1:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - "~/.yarn/docker-cache:/home/node/.cache/yarn:cached"
      - "~/.npm/docker-cache:/home/node/.npm:cached" 
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    

  ms2:
    container_name: ms2
    build:
      context: ./code/ms2
      dockerfile: Dockerfile
    volumes:
      - ./code/ms2:/usr/src/app:delegated
      - /usr/src/app/node_modules
      - "~/.yarn/docker-cache:/home/node/.cache/yarn:cached"
      - "~/.npm/docker-cache:/home/node/.npm:cached" 
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_CONFIG_FILE: "/etc/rabbitmq/rabbitmq.conf"
    

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile.nginx
    ports:
      - "80:80"
    
networks:
  ms-network:
    driver: bridge